## 데이터 로드 및 기본 탐색

In [5]:
# %% [Setup] 패키지 import
import pandas as pd
import numpy as np
import os

In [6]:
# %% [1] 데이터 로드
# ============================================================
# 1. 데이터 로드
# ============================================================
print("=" * 65)
print("  [실습 3] CSIC 2010 HTTP 데이터 로드 및 기본 탐색")
print("=" * 65)

# Jupyter 셀 모드에서도 동작하도록 __file__ 처리
try:
    SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
except NameError:
    SCRIPT_DIR = os.getcwd()

data_path = os.path.join(SCRIPT_DIR, "csic2010_requests.csv")

if not os.path.exists(data_path):
    print(f"\n  !! csic2010_requests.csv 파일이 없습니다.")
    print(f"  >> 먼저 download_csic2010.py를 실행하세요.")
    exit()

df = pd.read_csv(data_path)

print(f"\n  데이터 로드 완료!")
print(f"  파일: {data_path}")
print(f"  크기: {df.shape[0]:,}행 x {df.shape[1]}열")

=================================================================
  [실습 3] CSIC 2010 HTTP 데이터 로드 및 기본 탐색
=================================================================

  데이터 로드 완료!
  파일: /content/csic2010_requests.csv
  크기: 10,000행 x 18열

In [7]:
df.shape

(10000, 18)

In [8]:

df.describe()

       classification
count    10000.000000
mean         0.410500
std          0.491949
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          1.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   label            10000 non-null  object
 1   method           10000 non-null  object
 2   url              9961 non-null   object
 3   http_version     10000 non-null  object
 4   host             10000 non-null  object
 5   user_agent       10000 non-null  object
 6   pragma           10000 non-null  object
 7   cache_control    10000 non-null  object
 8   accept           9929 non-null   object
 9   accept_encoding  10000 non-null  object
 10  accept_charset   10000 non-null  object
 11  language         10000 non-null  object
 12  cookie           10000 non-null  object
 13  content_type     3016 non-null   object
 14  content_length   3016 non-null   object
 15  connection       10000 non-null  object
 16  body             3016 non-null   object
 17  classification   10000 non-null  int64
dtypes: int64(1), object(17)
memory usage: 1.4+ MB

In [10]:
df.tail()

,label,method,url,http_version,host,user_agent,pragma,cache_control,accept,accept_encoding,accept_charset,language,cookie,content_type,content_length,connection,body,classification
9995,Normal,GET,/tienda1/global/estilos.css,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=E920E69471A011579F0720FCD90BFF2E,NaN,NaN,close,NaN,0
9996,Normal,GET,/tienda1/imagenes/cmenbul.gif,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=36E12256C60662E0852525C2A204DEED,NaN,NaN,close,NaN,0
9997,Normal,GET,/tienda1/global/titulo.jsp,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=25D7022C3B580D1D6689811BF346DCB5,NaN,NaN,close,NaN,0
9998,Normal,POST,/tienda1/publico/anadir.jsp,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=2436A5157F43E5E3DECE11F1C390CFF8,application/x-www-form-urlencoded,Content-Length: 71,Connection: close,id=3&nombre=Queso+Manchego&precio=85&cantidad=...,0
9999,Anomalous,POST,/tienda1/publico/caracteristicas.jsp,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=AAECDF742DAEAD8C3F901AF615560423,application/x-www-form-urlencoded,Content-Length: 5,Connection: close,idA=2,1

In [11]:
df.nunique()

label                  2
method                 3
url                 2692
http_version           1
host                   2
user_agent             1
pragma                 1
cache_control          1
accept                 1
accept_encoding        1
accept_charset         1
language               1
cookie             10000
content_type           1
content_length       273
connection             2
body                2184
classification         2
dtype: int64

In [12]:
df.loc[df["content_length"].isna(), "method"].value_counts()

method
GET    6984
Name: count, dtype: int64

In [13]:
print(f"\n{'─' * 65}")
print("  [2] 데이터 기본 정보")
print(f"{'─' * 65}")

print(f"\n  전체 HTTP 요청 수: {len(df):,}건")
print(f"  컬럼 수: {df.shape[1]}개")
print(f"  메모리 사용량: {df.memory_usage(deep=True).sum() / 1024 / 1024:.1f} MB")

─────────────────────────────────────────────────────────────────
  [2] 데이터 기본 정보
─────────────────────────────────────────────────────────────────

  전체 HTTP 요청 수: 10,000건
  컬럼 수: 18개
  메모리 사용량: 11.9 MB

In [14]:
# %% [4] 라벨 분포 ★★★ (Normal vs Anomalous)
# ============================================================
# 4. 라벨(Label) 분포 확인 ★★★
# ============================================================
print(f"\n{'─' * 65}")
print("  [4] 라벨 분포 (Normal vs Anomalous) ★")
print(f"{'─' * 65}")

label_counts = df["label"].value_counts()
label_ratio = df["label"].value_counts(normalize=True) * 100

print(f"\n  {'라벨':<15s} | {'건수':>8s} | {'비율':>6s} | 시각화")
print(f"  {'─' * 15}-+-{'─' * 8}-+-{'─' * 6}-+-{'─' * 30}")

for label in label_counts.index:
    count = label_counts[label]
    ratio = label_ratio[label]
    bar = "█" * int(ratio / 2)
    print(f"  {label:<15s} | {count:>8,} | {ratio:>5.1f}% | {bar}")

print(f"\n  >> 정상({label_counts.get('Normal', 0):,}건) vs "
      f"공격({label_counts.get('Anomalous', 0):,}건)")

─────────────────────────────────────────────────────────────────
  [4] 라벨 분포 (Normal vs Anomalous) ★
─────────────────────────────────────────────────────────────────

  라벨              |       건수 |     비율 | 시각화
  ───────────────-+-────────-+-──────-+-──────────────────────────────
  Normal          |    5,895 |  59.0% | █████████████████████████████
  Anomalous       |    4,105 |  41.0% | ████████████████████

  >> 정상(5,895건) vs 공격(4,105건)

In [15]:
df["label"].value_counts()

label
Normal       5895
Anomalous    4105
Name: count, dtype: int64

In [16]:
print(f"\n{'─' * 65}")
print("  [5] HTTP 메서드 분포")
print(f"{'─' * 65}")

method_counts = df["method"].value_counts()
for method, count in method_counts.items():
    pct = count / len(df) * 100
    bar = "█" * int(pct / 2)
    print(f"  {method:6s}: {count:>8,}건 ({pct:5.1f}%) {bar}")

─────────────────────────────────────────────────────────────────
  [5] HTTP 메서드 분포
─────────────────────────────────────────────────────────────────
  GET   :    6,984건 ( 69.8%) ██████████████████████████████████
  POST  :    2,945건 ( 29.4%) ██████████████
  PUT   :       71건 (  0.7%)

In [17]:
print(f"\n{'─' * 65}")
print("  [7] 실제 HTTP 요청 샘플 확인 ★")
print(f"{'─' * 65}")

# 정상 요청 1건
print(f"\n  ═══ 정상 요청 (Normal) ═══")
normal = df[df["label"] == "Normal"].iloc[0]
print(f"  메서드: {normal['method']}")
print(f"  URL:    {normal['url'][:100]}{'...' if len(str(normal['url'])) > 100 else ''}")
print(f"  쿠키:   {str(normal['cookie'])[:60]}{'...' if len(str(normal['cookie'])) > 60 else ''}")
body = str(normal["body"]) if pd.notna(normal["body"]) and normal["body"] else "(없음)"
print(f"  본문:   {body[:100]}")

# 공격 요청 3건
print(f"\n  ═══ 공격 요청 (Anomalous) — 3건 ═══")
anomalous = df[df["label"] == "Anomalous"].sample(3, random_state=42)
for i, (_, row) in enumerate(anomalous.iterrows(), 1):
    print(f"\n  --- 공격 #{i} ---")
    print(f"  메서드: {row['method']}")
    url_display = str(row["url"])[:120]
    print(f"  URL:    {url_display}{'...' if len(str(row['url'])) > 120 else ''}")
    body = str(row["body"]) if pd.notna(row["body"]) and row["body"] else "(없음)"
    print(f"  본문:   {body[:120]}{'...' if len(body) > 120 else ''}")
    print(f"  → 1교시에서 배운 공격 패턴을 찾아보세요!")

─────────────────────────────────────────────────────────────────
  [7] 실제 HTTP 요청 샘플 확인 ★
─────────────────────────────────────────────────────────────────

  ═══ 정상 요청 (Normal) ═══
  메서드: GET
  URL:    /tienda1/miembros/imagenes/ogono.jpg
  쿠키:   JSESSIONID=FDC7D99F5F76056DB0AF6D58232FA236
  본문:   (없음)

  ═══ 공격 요청 (Anomalous) — 3건 ═══

  --- 공격 #1 ---
  메서드: GET
  URL:    /WebSphereSamples/SingleSamples/Increment/increment.html
  본문:   (없음)
  → 1교시에서 배운 공격 패턴을 찾아보세요!

  --- 공격 #2 ---
  메서드: GET
  URL:    /tienda1/publico/carrito.jsp/asf-logo-wide
  본문:   (없음)
  → 1교시에서 배운 공격 패턴을 찾아보세요!

  --- 공격 #3 ---
  메서드: GET
  URL:    /tienda1/global/estilos.css/asf-logo-wide.gif/.Old
  본문:   (없음)
  → 1교시에서 배운 공격 패턴을 찾아보세요!

In [18]:
print(f"\n{'─' * 65}")
print("  [8] URL 길이 기본 통계")
print(f"{'─' * 65}")

df["url_length"] = df["url"].str.len()

print(f"\n  {'구분':<12s} | {'평균':>8s} | {'중앙값':>8s} | {'최대':>8s}")
print(f"  {'─' * 12}-+-{'─' * 8}-+-{'─' * 8}-+-{'─' * 8}")

for label in ["Normal", "Anomalous"]:
    subset = df[df["label"] == label]["url_length"]
    print(f"  {label:<12s} | {subset.mean():>8.0f} | {subset.median():>8.0f} | {subset.max():>8,}")

print(f"\n  >> 공격 요청의 URL이 평균적으로 더 깁니다! (공격 코드가 삽입되므로)")

─────────────────────────────────────────────────────────────────
  [8] URL 길이 기본 통계
─────────────────────────────────────────────────────────────────

  구분           |       평균 |      중앙값 |       최대
  ────────────-+-────────-+-────────-+-────────
  Normal       |       51 |       29 |    332.0
  Anomalous    |       77 |       33 |    865.0

  >> 공격 요청의 URL이 평균적으로 더 깁니다! (공격 코드가 삽입되므로)

In [19]:
print(f"\n{'─' * 65}")
print("  [9] 데이터 품질 확인")
print(f"{'─' * 65}")

# 결측치 확인
missing = df.isnull().sum()
missing_cols = missing[missing > 0]
print(f"\n  결측치가 있는 컬럼:")
if len(missing_cols) > 0:
    for col, cnt in missing_cols.items():
        print(f"    - {col}: {cnt:,}건")
else:
    print("    없음 (body, cookie 등은 빈 문자열)")

# 빈 body (GET 요청)
empty_body = df["body"].fillna("").eq("").sum()
print(f"\n  본문(body)이 비어있는 요청: {empty_body:,}건 (대부분 GET 요청)")

print(f"\n{'=' * 65}")
print("  실습 3 완료! 다음: streamlit run eda_visualization.py")
print(f"{'=' * 65}")

─────────────────────────────────────────────────────────────────
  [9] 데이터 품질 확인
─────────────────────────────────────────────────────────────────

  결측치가 있는 컬럼:
    - url: 39건
    - accept: 71건
    - content_type: 6,984건
    - content_length: 6,984건
    - body: 6,984건
    - url_length: 39건

  본문(body)이 비어있는 요청: 6,984건 (대부분 GET 요청)

=================================================================
  실습 3 완료! 다음: streamlit run eda_visualization.py
=================================================================

In [20]:
df.tail()

,label,method,url,http_version,host,user_agent,pragma,cache_control,accept,accept_encoding,accept_charset,language,cookie,content_type,content_length,connection,body,classification,url_length
9995,Normal,GET,/tienda1/global/estilos.css,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=E920E69471A011579F0720FCD90BFF2E,NaN,NaN,close,NaN,0,27.0
9996,Normal,GET,/tienda1/imagenes/cmenbul.gif,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=36E12256C60662E0852525C2A204DEED,NaN,NaN,close,NaN,0,29.0
9997,Normal,GET,/tienda1/global/titulo.jsp,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=25D7022C3B580D1D6689811BF346DCB5,NaN,NaN,close,NaN,0,26.0
9998,Normal,POST,/tienda1/publico/anadir.jsp,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=2436A5157F43E5E3DECE11F1C390CFF8,application/x-www-form-urlencoded,Content-Length: 71,Connection: close,id=3&nombre=Queso+Manchego&precio=85&cantidad=...,0,27.0
9999,Anomalous,POST,/tienda1/publico/caracteristicas.jsp,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=AAECDF742DAEAD8C3F901AF615560423,application/x-www-form-urlencoded,Content-Length: 5,Connection: close,idA=2,1,36.0

In [21]:
df.describe()

       classification   url_length
count    10000.000000  9961.000000
mean         0.410500    61.536994
std          0.491949    78.103567
min          0.000000     1.000000
25%          0.000000    27.000000
50%          0.000000    29.000000
75%          1.000000    48.000000
max          1.000000   865.000000